#!/bin/sh -e
################################################################################

# build the library for the 
# Adafruit 64x64 RGB LED Matrix 2.5mm Pitch
# https://www.adafruit.com/product/3649
# Adafruit Matrix Bonnet
# https://www.adafruit.com/product/3211

url='https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/main/rgb-matrix.sh'

################################################################################

curl $url > rpi-rgb-led-matrix-installer

echo 'CONTINUE? [y/n] y'
echo '1. Adafruit RGB Matrix Bonnet'
echo '1. Quality (disables sound, requires soldering)'
echo 'CONTINUE? [y/n] y'
echo 'REBOOT NOW? [y/n] n'
sudo bash rpi-rgb-led-matrix-installer

cp rpi-rgb-led-matrix/lib/librgbmatrix.a .
chmod a=r librgbmatrix.a

cp rpi-rgb-led-matrix/include/led-matrix-c.h rgbmatrix.h
chmod a=r rgbmatrix.h

rm -r rpi-rgb-led-matrix rpi-rgb-led-matrix-installer

echo 'need to reboot'

################################################################################
