//******************************************************************************

#include "orient.h"
#include "mpu6050.h"

//******************************************************************************

void orient_create()
{
  accel_gyro_create(ACCEL_RANGE_4, GYRO_RANGE_500);
}

void orient_free()
{
  accel_gyro_free();
}

orient_t orient_get()
{
  int16_t x = accl_x();
  int16_t y = accl_y();
  int16_t z = accl_z();

  // generated by calib-orient
  x -= -2941;
  y -= 489;
  z -= -4977;

  // generated by calib-orient
  int16_t xx = (int16_t)((int32_t)x - (int32_t)y * 714 / 16438 - (int32_t)z * 585 / 16832);
  int16_t yy = (int16_t)((int32_t)y - (int32_t)x * -666 / 16441 - (int32_t)z * 172 / 16832);
  int16_t zz = (int16_t)((int32_t)z - (int32_t)x * -379 / 16441 - (int32_t)y * -378 / 16438);

  // generated by calib-orient
  xx = (int16_t)((int32_t)x * 2048 / 16441);
  yy = (int16_t)((int32_t)y * 2048 / 16438);
  zz = (int16_t)((int32_t)z * 2048 / 16832);

  // generated by calib-orient
  xx -= -1;
  yy -= 1;
  zz -= -5;

  if (xx > 1000)
    xx = 1000;
  if (xx < -1000)
    xx = -1000;

  if (yy > 1000)
    yy = 1000;
  if (yy < -1000)
    yy = -1000;

  if (zz > 1000)
    zz = 1000;
  if (zz < -1000)
    zz = -1000;

  orient_t orient = { -xx, -yy, zz };
  return orient;
}

//******************************************************************************
